// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function databaseUrl() {
  const url = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

  if (!url) {
    throw new Error("DIRECT_URL or DATABASE_URL must be set for Prisma CLI.");
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl(),
  },
});
